# Generated by Django 4.1.7 on 2023-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='details',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
